name: club-social

services:
  dev-container:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    command: sleep infinity
    volumes:
      - ../:/workspace:cached
      - node_modules:/workspace/node_modules

  maildev:
    image: maildev/maildev
    ports:
      - '1080:1080'
      - '1025:1025'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: club-social
    ports:
      - '5932:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker

volumes:
  redis_data:
  postgres_data:
  node_modules:
